server:
  port:9003
spring:
application:
  name:USERSERVICE

eureka:
  client:
        register-with-eureka:true
        fetch-registry:ture
  serviceUrl:
  defaultZone: http://localhost:8761/eureka/
